### ISSUE TITLE
Questions about testing on Kohler datasets

### ISSUE THREAD

**Issue by karentwan** [firenxygao/deblur#2]
Hi, your model was trained on the Gopro dataset and the dataset you created yourself, but can be tested directly on the Kohler dataset, I tested your model and found it in Kohler dataset also performed well. Did you use it to train on Kohler's blurred image?

**Comment by firenxygao** [comment]
We did not train on Kohler dataset.

xiaodao <notifications@github.com>于2019年11月28日 周四下午9:07写道：

**Comment by karentwan** [comment]
Thank you very much for your answer. I also have a supplementary question. You provided two models, one is Alldata and the other is Default. 
Do you use the training set provided by gopro to train the Default model, did you add Other blurred images to the training set? Do Alldata model training only use the data set you created yourself?
Your model also works very well on real blurred images!

**Comment by firenxygao** [comment]
The default model was trained on gopro dataset.
The alldata model was trained on gopro dataset plus our own created dataset.
No other images were used for training.

xiaodao <notifications@github.com> 於 2019年11月29日 週五 下午7:40寫道：

**Comment by karentwan** [comment]
Thanks for your answer
