### ISSUE TITLE
Test Time on GOPRO evaluation dataset

### ISSUE THREAD

**Issue by yff0815** [firenxygao/deblur#3]
Hello! Thank you for releasing the code. I would like to know the time in table 3 of the paper is the test time of all test sets or the test time of one image? Looking forward to your reply, Thank you! 
![image](https://user-images.githubusercontent.com/41831614/70894579-3e0c5e00-2028-11ea-9bb8-da72f89d2cf7.png)

**Comment by firenxygao** [comment]
The reported time in the table is for one image of dimension 960*1280

yff0815 <notifications@github.com> 於 2019年12月16日 週一 下午5:19寫道：

**Comment by yff0815** [comment]
Thank you so much!
